### ISSUE TITLE
issue: pre-release aws credentials required on import 

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-model#73]
* nzshm-model version: pre-release
* Python version: 3.10
* Operating System: Ubuntu

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did
try to import nzshm_model
```
>>> from nzshm_model import branch_registry
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/GNSDATA/.cache/pypoetry/virtualenvs/toshi-hazard-store-ANifN6pQ-py3.10/lib/python3.10/site-packages/nzshm_model/__init__.py", line 42, in <module>
    from .model import NshmModel
  File "/GNSDATA/.cache/pypoetry/virtualenvs/toshi-hazard-store-ANifN6pQ-py3.10/lib/python3.10/site-packages/nzshm_model/model.py", line 11, in <module>
    from nzshm_model.psha_adapter.openquake import NrmlDocument, OpenquakeSimplePshaAdapter
  File "/GNSDATA/.cache/pypoetry/virtualenvs/toshi-hazard-store-ANifN6pQ-py3.10/lib/python3.10/site-packages/nzshm_model/psha_adapter/openquake/__init__.py", line 14, in <module>
    from .simple_nrml import OpenquakeSimplePshaAdapter, gmcm_branch_from_element_text
  File "/GNSDATA/.cache/pypoetry/virtualenvs/toshi-hazard-store-ANifN6pQ-py3.10/lib/python3.10/site-packages/nzshm_model/psha_adapter/openquake/simple_nrml.py", line 14, in <module>
    from .toshi import API_KEY, API_URL, SourceSolution
  File "/GNSDATA/.cache/pypoetry/virtualenvs/toshi-hazard-store-ANifN6pQ-py3.10/lib/python3.10/site-packages/nzshm_model/psha_adapter/openquake/toshi.py", line 8, in <module>
    from nzshm_model.logic_tree.source_logic_tree.toshi_api import get_secret
  File "/GNSDATA/.cache/pypoetry/virtualenvs/toshi-hazard-store-ANifN6pQ-py3.10/lib/python3.10/site-packages/nzshm_model/logic_tree/source_logic_tree/toshi_api.py", line 155, in <module>
    API_KEY = get_secret("NZSHM22_TOSHI_API_SECRET_PROD", "us-east-1").get("NZSHM22_TOSHI_API_KEY_PROD")
```

**Comment by chrisdicaprio** [comment]
This happens if you have envvar `NZSHM22_TOSHI_API_URL` set to something containing `"PROD"` or `"TEST"` but no AWS credentials. This is unlikely to happen.

**Comment by chrisdicaprio** [comment]
won't fix
